### ISSUE TITLE
App crashes after orientation change in ImageActivity

### ISSUE THREAD

**Issue by LeoLamCY** [tanallnight/Blip#6]
The app crashes when an ImageActivity is closed after orientation changes (while viewing a comic, change from portrait to landscape back to portrait).
The error given is "The ImageView's ScaleType has been changed since attaching a PhotoViewAttacher");

The crash doesn't occur if you comment out the line: 

```
ViewCompat.setTransitionName(photo, EXTRA_IMAGE);
```

on line 81 in ImageActivity.java

so the crash seems to be related to transitions between activities.

**Comment by tanallnight** [comment]
Thanks, i removed the transition as i could not get PhotoView to cooperate
